### ISSUE TITLE
PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

### ISSUE THREAD

**Issue by dkavraal** [davedoesdev/python-jwt#15]
It seems I have an issue with multithreading opportunity.
Hasn't the same emerged to any of you?

**Preinfo** 
Python 2.7.3
/etc/debian_version ==> 7.11
uwsgi --version ==> 1.2.3-debian
pip freeze: python-jwt==2.0.1
pip freeze: cryptography==1.7.1

**Debug**
```bash
$ uwsgi --http-socket 127.0.0.1:6000 --plugin python --callable app --module firebase --enable-threads --master --processes 8 --vacuum --uid www-data --gid www-data --chdir /privacy/ --max-requests 100 --harakiri 300 --post-buffering 8192 firebase.py
	INFO 2016-12-23 20:02:38,844 firebase 27535 140618739799904 {'action': 'genToken'}
	Firebase login error: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
	ERROR 2016-12-23 20:02:38,849 firebase 27535 140618739799904 {'action': 'login', 'error': 'PID check failed. RNG must be
	 re-initialized after fork(). Hint: Try Random.atfork()', 'desc': 'firebase token gen error. '}
	Traceback (most recent call last):
	  File "./firebase.py", line 83, in genToken
	    datetime.timedelta(seconds=3600))
	  File "/usr/local/lib/python2.7/dist-packages/python_jwt/__init__.py", line 98, in generate_jwt
	    '' if header['alg'] == 'none' else jws.sign(header, claims, priv_key).decode('utf-8')
	  File "/usr/local/lib/python2.7/dist-packages/jws/__init__.py", line 29, in sign
	    signature = signer(_signing_input(head, payload, is_json), key)
	  File "/usr/local/lib/python2.7/dist-packages/jws/algos.py", line 74, in sign
	    return self.padder.new(key).sign(self.hashm)             # pycrypto 2.5
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/Signature/PKCS1_v1_5.py", line 112, in sign
	    m = self._key.decrypt(em)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 174, in decrypt
	    return pubkey.pubkey.decrypt(self, ciphertext)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/PublicKey/pubkey.py", line 93, in decrypt
	    plaintext=self._decrypt(ciphertext)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 235, in _decrypt
	    r = getRandomRange(1, self.key.n-1, randfunc=self._randfunc)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/Util/number.py", line 123, in getRandomRange
	    value = getRandomInteger(bits, randfunc)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/Util/number.py", line 104, in getRandomInteger
	    S = randfunc(N>>3)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
	    return self._singleton.read(bytes)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
	    return _UserFriendlyRNG.read(self, bytes)
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
	    self._check_pid()
	  File "/usr/local/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
	    raise AssertionError("PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()")
	AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()


$ uwsgi --http-socket 127.0.0.1:6000 --plugin python --callable app --module firebase firebase.py

	no errors. it runs ok.

$ uwsgi --http-socket 127.0.0.1:6000 --plugin python --callable app --module firebase --enable-threads firebase.py

	no errors. it runs ok.

$ uwsgi --http-socket 127.0.0.1:6000 --plugin python --callable app --module firebase --master firebase.py

	exception fired.

$ uwsgi --http-socket 127.0.0.1:6000 --plugin python --callable app --module firebase --processes 8 --uid www-data --gid www-data --harakiri 300 --max-requests 100 --enable-threads --stats 127.0.0.1:3005 --chdir /privacy/ --vacuum --chmod-socket 666 --post-buffering 8192 firebase.py

	exception fired.
```

**Basically this is the generator:**

```python
...
import python_jwt as jwt
import Crypto.PublicKey.RSA as RSA
...
__FIREBASE_SERVICE_ACCOUNT_EMAIL = "my project ... @ google service account stuff.com"
__FIREBASE_PRIVATE_KEY = RSA.importKey("-----BEGIN PRIVATE KEY-----\n..... the secret")

def genToken(userid, username):
    l.info({'action': 'genToken'})
    authKey = ''
    try:
        authKey = jwt.generate_jwt({'iss': __FIREBASE_SERVICE_ACCOUNT_EMAIL,
                       'sub': __FIREBASE_SERVICE_ACCOUNT_EMAIL,
                       'aud': "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
                       'uid': userid,
                       'claims': {
                                  'premium_account': False,
                                  'NAME': username
                                  }
                       },
                      __FIREBASE_PRIVATE_KEY,
                      'RS256',
                      datetime.timedelta(seconds=3600))
    except Exception as e:
        print("Firebase login error: %s" % e)
        l.exception({"action": "login", "desc": "firebase token gen error.", "error": "%s" % e.message})

    return authKey
```

**Comment by davedoesdev** [comment]
Looks like this isn't specify to python-jwt but any time you use pycrypto with threads, you need to call `Random.atfork`.

This post shows someone having a similar problem with uwsgi. It seems you can use a hook to get it done; https://groups.google.com/forum/#!topic/pylons-discuss/ZshUsxp59RY

**Comment by dkavraal** [comment]
Thanks that did the trick.


```python

import uwsgi
from Crypto.Random import atfork

def postfork_chain_hook():
    try:
        atfork()
    except Exception as e:
        print(e)

uwsgi.post_fork_hook = postfork_chain_hook
```
