### ISSUE TITLE
Install with pip

### ISSUE THREAD

**Issue by ffhex** [davedoesdev/python-jwt#8]
Hi,
although I have tried many times the process of installing this package with pip on Linux, it does not work. It always ends with a broken installation and setting up files on ''/usr/local/local/lib/python2.7/dist-packages/'.
Here is the verbose output of the pip command(pip -vvv install python_jwt)
```
Downloading python_jwt-1.0.0.tar.gz (447kB):
  Downloading from URL https://pypi.python.org/packages/source/p/python_jwt/python_jwt-1.0.0.tar.gz#md5=12a7f8b44a7345f7db6abb348f7d348a (from https://pypi.python.org/simple/python-jwt/)
...Downloading python_jwt-1.0.0.tar.gz (447kB): 447kB downloaded
  Running setup.py (path:/tmp/pip_build_root/python-jwt/setup.py) egg_info for package python-jwt
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'home_page'
      warnings.warn(msg)
    running egg_info
    running build
    running config
  Source in /tmp/pip_build_root/python-jwt has version 1.0.0, which satisfies requirement python-jwt
Requirement already satisfied (use --upgrade to upgrade): jws>=0.1.2 in /usr/local/lib/python2.7/dist-packages (from python-jwt)
Installing collected packages: python-jwt
  Running setup.py install for python-jwt
    Running command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/python-jwt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OC2che-record/install-record.txt --single-version-externally-managed --compile
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'home_page'
      warnings.warn(msg)
    running install
    /tmp/pip_build_root/python-jwt/dist/.bentomaker.py-0.1-07628d92704c3a8f4413b0c74c228d35/bento/distutils/commands/install.py:59: UserWarning: --compile option is ignored.
      warnings.warn("--compile option is ignored.")
    running build
    running config
Successfully installed python-jwt
```
Here is the destination directory after the install:
```
/usr/local/local/lib/python2.7/dist-packages/python_jwt-1.0.0-py2.7.egg-info
```
Thanks

**Comment by davedoesdev** [comment]
Could you try in a virtualenv?

```shell
david@david-Latitude-E6440:/tmp$ virtualenv foo
Running virtualenv with interpreter /usr/bin/python2
New python executable in foo/bin/python2
Also creating executable in foo/bin/python
Installing setuptools, pip...done.
david@david-Latitude-E6440:/tmp$ source ./foo/bin/activate
(foo)david@david-Latitude-E6440:/tmp$ which pip
/tmp/foo/bin/pip
(foo)david@david-Latitude-E6440:/tmp$ pip install python_jwt
Downloading/unpacking python-jwt
  Downloading python_jwt-1.0.0.tar.gz (447kB): 447kB downloaded
  Running setup.py (path:/tmp/foo/build/python-jwt/setup.py) egg_info for package python-jwt
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'home_page'
      warnings.warn(msg)
Downloading/unpacking jws>=0.1.2 (from python-jwt)
  Downloading jws-0.1.3.tar.gz
  Running setup.py (path:/tmp/foo/build/jws/setup.py) egg_info for package jws
    
Installing collected packages: python-jwt, jws
  Running setup.py install for python-jwt
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'home_page'
      warnings.warn(msg)
    /tmp/foo/build/python-jwt/dist/.bentomaker.py-0.1-07628d92704c3a8f4413b0c74c228d35/bento/distutils/commands/install.py:56: UserWarning: --install-headers option is ignored.
      warnings.warn("--install-headers option is ignored.")
    /tmp/foo/build/python-jwt/dist/.bentomaker.py-0.1-07628d92704c3a8f4413b0c74c228d35/bento/distutils/commands/install.py:59: UserWarning: --compile option is ignored.
      warnings.warn("--compile option is ignored.")
  Running setup.py install for jws
    
Successfully installed python-jwt jws
Cleaning up...
(foo)david@david-Latitude-E6440:/tmp$ which python
/tmp/foo/bin/python
(foo)david@david-Latitude-E6440:/tmp$ python
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwt
```

**Comment by ffhex** [comment]
ok, although some I had to resolve simplejson dependency with a separate command, it works with virtualenv:
```
tinybuntu% virtualenv foo                                                                                                                    ~/sd/never-ending-work/cce/cce
New python executable in foo/bin/python
Installing setuptools, pip...done.
tinybuntu% source ./foo/bin/activate                                                                                                         ~/sd/never-ending-work/cce/cce
(foo)tinybuntu% which pip                                                                                                                    ~/sd/never-ending-work/cce/cce
/mnt/ffpad/ff/sd/never-ending-work/cce/cce/foo/bin/pip
(foo)tinybuntu%                                                                                                                              ~/sd/never-ending-work/cce/cce
(foo)tinybuntu% pip install python_jwt                                                                                                       ~/sd/never-ending-work/cce/cce
Collecting python-jwt
  Downloading python_jwt-1.0.0.tar.gz (447kB)
    100% |################################| 450kB 243kB/s
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'home_page'
      warnings.warn(msg)
Collecting jws>=0.1.2 (from python-jwt)
  Downloading jws-0.1.3.tar.gz
Installing collected packages: jws, python-jwt
  Running setup.py install for jws
  Running setup.py install for python-jwt
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'summary'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'home_page'
      warnings.warn(msg)
    /tmp/pip-build-HfDFIs/python-jwt/dist/.bentomaker.py-0.1-07628d92704c3a8f4413b0c74c228d35/bento/distutils/commands/install.py:56: UserWarning: --install-headers option is ignored.
      warnings.warn("--install-headers option is ignored.")
    /tmp/pip-build-HfDFIs/python-jwt/dist/.bentomaker.py-0.1-07628d92704c3a8f4413b0c74c228d35/bento/distutils/commands/install.py:59: UserWarning: --compile option is ignored.
      warnings.warn("--compile option is ignored.")
  Could not find .egg-info directory in install record for python-jwt
Successfully installed jws-0.1.3 python-jwt
(foo)tinybuntu% which python                                                                                                                 ~/sd/never-ending-work/cce/cce
/mnt/ffpad/ff/sd/never-ending-work/cce/cce/foo/bin/python
(foo)tinybuntu% python                                                                                                                       ~/sd/never-ending-work/cce/cce
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jwt/__init__.py", line 15, in <module>
    import simplejson as json
ImportError: No module named simplejson
>>>
(foo)tinybuntu% pip install simplejson                                                                                                       ~/sd/never-ending-work/cce/cce
Collecting simplejson
  Downloading simplejson-3.6.5.tar.gz (73kB)
    100% |################################| 77kB 231kB/s
Installing collected packages: simplejson
  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/temp.linux-x86_64-2.7/simplejson/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/simplejson/_speedups.o -o build/lib.linux-x86_64-2.7/simplejson/_speedups.so
Successfully installed simplejson-3.6.5
(foo)tinybuntu% python                                                                                                                       ~/sd/never-ending-work/cce/cce
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwt
>>>

```
It could be a problem with the native host setup of the ptyhon environment - although I have just used a standard Ubuntu 14.04 image and installed the standard python packages (2.7). I will try to investigate more in depth as soon as I will have some time.
Thanks

**Comment by davedoesdev** [comment]
That's strange! Current version doesn't have

```python
import simplejson as json
```

**Comment by davedoesdev** [comment]
@ffhex Do you have another {{jwt/__init__.py}} in your environment, such as this?

https://github.com/mozilla-services/signing-service/blob/master/signing/jwt.py

Python packaging is a disaster zone.

**Comment by ffhex** [comment]
Dave, you are right!
I have an old one... (now removed) hidden in a old working directory and... you know already there are many python based implementation of jwt but yours is probably the best as far as I can see.

**Comment by davedoesdev** [comment]
Thanks @ffhex - let me know if you have any problems using it.
